namespace: "orionuser1"
name: "collection_plugin_testing"
version: "0.0.20"
license:
  - MIT
readme: "README.md"
authors:
  - "Calvin Spealman <cspealma@redhat.com>"
description: "A set of test plugins of every type"
dependencies:
repository:
documentation:
homepage:
issues:
